/* #
# Author: wangchunxin
# Created Time: 2020/11/26 11:41 上午
# File Name:
# Description:
# */
package config

const BASE_URL = "https://ad.oceanengine.com/open_api/"

const VERSION = "2"

const (
	//ADVERTISER_GET_URI                   = "/agent/advertiser/select/"              // 广告主列表
	//ADVERTISER_ADD_URI                   = "/agent/advertiser/create/"              // 创建广告主
	//ADVERTISER_UPDATE_URI                = "/agent/advertiser/update/"              // 修改广告主
	//CAMPAIGN_GET_URI                     = "/campaign/get/"                         // 获取广告组
	//CAMPAGIN_ADD_URI                     = "/campaign/create/"                      // 创建广告组
	//CAMPAGIN_UPDATE_URI                  = "/campaign/update/"                      // 修改广告组
	//CAMPAGIN_UPDATE_STATUS_URI           = "/campaign/update/status/"               // 广告组更新状态
	//AD_GET_URI                           = "/ad/get/"                               // 获取计划
	//AD_ADD_URI                           = "/ad/create/"                            // 添加计划
	//AD_UPDATE_URI                        = "/ad/update/"                            // 修改计划
	//AD_UPDATE_STATUS_URI                 = "/ad/update/status/"                     // 修改状态
	//AD_UPDATE_BUDGET_URI                 = "/ad/update/budget/"                     // 修改计划预算
	//AD_UPDATE_BID_URI                    = "/ad/update/bid/"                        // 修改计划出价
	//AD_REJECT_REASON_URI                 = "/ad/reject_reason/"                     // 获取计划审核建议
	//CREATIVE_GET_URI                     = "/creative/get/"                         // 获取创意列表
	//CREATIVE_ADD_URI                     = "/creative/create/"                      // 创建创意
	//CREATIVE_UPDATE_URI                  = "/creative/update/"                      // 修改创意
	//CREATIVE_READ_V2_URI                 = "/creative/read_v2/"                     // 创意详情信息
	//CREATIVE_UPDATE_STATUS_URI           = "/creative/update/status"                // 修改创意状态
	//CREATIVE_MATERIAL_READ_URI           = "/creative/material/read/"               // 创意素材详情
	//CREATIVE_REJECT_REASON_URI           = "/creative/reject_reason/"               // 获取创意审核建议
	//REPORT_AGENT_GET                     = "/report/agent/get_v2/"                  // 代理商数据
	//REPORT_ADVERTISER_GET                = "/report/advertiser/get/"                //广告主数据
	//REPORT_CAMPAIFN_GET                  = "/report/campaign/get/"                  // 广告组数据
	//REPORT_AD_GET                        = "/report/ad/get/"                        // 广告计划数据
	//REPORT_CREATIVE_GET                  = "/report/creative/get/"                  // 广告创意数据
	//REPORT_INTEGRATED_GET                = "/report/integrated/get/"                // 多合一报表
	//REPORT_VIDEO_GET                     = "/report/video/get/"                     // 视频素材报表
	//REPORT_VIDEO_FRAME_GET               = "/report/video/frame/get/"               // 视频互动流失数据
	//REPORT_AUDIENCE_INTEREST_ACTION_LIST = "/report/audience/interest_action/list/" // 受众-行为兴趣数据
	//REPORT_AUDIENCE_AWEME_LIST           = "/report/audience/aweme/list/"           // 受众-抖音达人数据
	//REPORT_AUDIENCE_PROVINCE             = "/report/audience/province/"             // 受众-省份数据
	//REPORT_AUDIENCE_CITY                 = "/report/audience/city/"                 // 受众-城市数据
	//REPORT_AUDIENCE_GENDER               = "/report/audience/gender/"               // 受众-性别数据
	//REPORT_AUDIENCE_TAG                  = "/report/audience/tag/"                  // 受众-兴趣数据
	//REPORT_AUDIENCE_AGE                  = "/report/audience/age/"                  // 受众-年龄数据
	//REPORT_MISTY_GET                     = "/report/misty/get/"                     // 分组模糊数据
	//TOOL_ESTIMATE_AUDIENCE               = "/tools/estimate_audience/"              // 查询受众预估结果
	//TOOL_APP_SEARCH                      = "/tools/app_search/"                     //查询应用信息
	//TOOL_BID_SUGGEST                     = "/tools/bid/suggest/"                    //建议日预算及预期成本
	//TOOL_AD_QUALITY_GET                  = "/tools/ad_quality/get/"                 //查询广告质量度
	//TOOL_INDUSTORY_GET                   = "/tools/industry/get/"                   //获取行业列表
	//TOOL_REGION_GET                      = "/tools/region/get/"                     // 获取地域列表
	//TOOL_ADVETISER_GOODS_LIST            = "/tools/advertiser_goods/list/"          // 获取鲁班商品列表
	//TOOL_AD_PREVIEW_QRCODE_GET           = "/tools/ad_preview/qrcode_get/"          // 获取广告预览二维码
	//TOOL_LES_ACCOUNT_SEARCH              = "/tools/ies_account_search/"             // 获取绑定的抖音号
	//TOOL_ADVERTISER_PACKAGE_GET          = "/tools/advertiser_package/get/"         // 查询极速下载列表
	//TOOL_LOG_SEARCH                      = "/tools/log_search/"                     // 日志查询
	//TOOL_PROCEDURAL_PACKAGE_GET          = "/tools/procedural_package/get/"         // 查询程序化创意包
	//TOOL_ACTION_TEXT_GET                 = "/tools/action_text/get/"                // 行动号召字段内容获取
	//TOOL_AD_STAT_EXTRA_INFO_GET          = "/tools/ad_stat_extra_info/get/"         // 查询广告计划学习期状态
	//TOOL_PROMOTION_CARD_RECOMMEND_GET    = "/tools/promotion_card/recommend/get/"   // 查询推广卡片推荐内容
	//TOOL_AWEME_INFO_SEARCH               = "/tools/aweme_info_search/"              // 查询抖音帐号和类目信息

	AD_CREATE_URI                                               = "/ad/create/"                                             //广告计划
	AD_GET_URI                                                  = "/ad/get/"                                                  //获取广告计划
	AD_REJECT_REASON_URI                                        = "/ad/reject_reason/"                                        //获取计划审核建议
	AD_UPDATE_URI                                               = "/ad/update/"                                               //修改广告计划
	AD_UPDATE_BID_URI                                           = "/ad/update/bid/"                                           //更新计划出价
	AD_UPDATE_BUDGET_URI                                        = "/ad/update/budget/"                                        //更新计划预算
	AD_UPDATE_STATUS_URI                                        = "/ad/update/status/"                                        //更新计划状态

	ADLAB_ADS_GET_URI                                           = "/adlab/ads/get/"
	ADLAB_GROUP_GET_URI                                         = "/adlab/group/get/"                                         //获取项目信息
	ADLAB_GROUP_CONVERT_UPDATE_URI                              = "/adlab/group_convert/update/"                              //设置项目转化信息 //批量查询计划信息
	ADLAB_ADS_BUDGET_APPEND_URI                                 = "/adlab/ads_budget/append/"                                 //追加项目计划预算
	ADLAB_AD_BID_UPDATE_URI                                     = "/adlab/ad_bid/update/"                                     //更新计划目标成本
	ADLAB_AD_BUDGET_CANCEL_URI                                  = "/adlab/ad_budget/cancel/"                                  //取消追加计划预算
	ADLAB_AD_STATUS_UPDATE_URI                                  = "/adlab/ad_status/update/"                                  //更新计划状态
	ADLAB_BUDGET_GET_URI                                        = "/adlab/budget/get/"                                        //获取追加预算信息
	ADLAB_GROUP_CREATE_URI                                      = "/adlab/group/create/"                                      //新建投放管家项目
	ADLAB_GROUPS_GET_URI                                        = "/adlab/groups/get/"                                        //获取项目列表
	ADLAB_GROUP_ADS_GET_URI                                     = "/adlab/group_ads/get/"                                    //获取计划列表
	ADLAB_GROUP_AUDIENCE_UPDATE_URI                             = "/adlab/group_audience/update/"                             //设置项目定向信息
	ADLAB_GROUP_BUDGET_UPDATE_URI                               = "/adlab/group_budget/update/"                               //设置项目预算信息
	ADLAB_GROUP_CREATIVE_UPDATE_URI                             = "/adlab/group_creative/update/"                             //设置项目创意信息
	ADLAB_GROUP_MATERIAL_INFO_GET_URI                           = "/adlab/group_material_info/get/"                           //获取项目素材信息
	ADLAB_GROUP_STATUS_UPDATE_URI                               = "/adlab/group_status/update/"                               //更新项目状态

	ADVERTISER_AVATAR_SUBMIT_URI                                = "/advertiser/avatar/submit/"                                //上传/更新账户头像
	ADVERTISER_AVATAR_GET_URI                                   = "/advertiser/avatar/get/"                                 //获取广告主头像信息
	ADVERTISER_BUDGET_GET_URI                                   = "/advertiser/budget/get/"                                   //获取账户日预算
	ADVERTISER_FUND_DAILY_STAT_URI                              = "/advertiser/fund/daily_stat/"                              //查询账号日流水
	ADVERTISER_FUND_GET_URI                                     = "/advertiser/fund/get/"                                     //查询账号余额
	ADVERTISER_FUND_TRANSACTION_GET_URI                         = "/advertiser/fund/transaction/get/"                         //查询账号流水明细
	ADVERTISER_INFO_URI                                         = "/advertiser/info/"                                         //广告主信息
	ADVERTISER_PUBLIC_INFO_URI                                  = "/advertiser/public_info/"                                  //广告主公开信息
	ADVERTISER_QUALIFICATION_CREATE_URI                         = "/advertiser/qualification/create/"                         //新增投放资质
	ADVERTISER_QUALIFICATION_GET_URI                            = "/advertiser/qualification/get/"                            //获取广告主资质
	ADVERTISER_QUALIFICATION_SELECT_URI                         = "/advertiser/qualification/select/"                         //获取投放资质信息（待废弃）
	ADVERTISER_QUALIFICATION_SELECT_V2__URI                     = "/advertiser/qualification/select_v2/ "                     //获取投放资质信息（新版）
	ADVERTISER_QUALIFICATION_SUBMIT_URI                         = "/advertiser/qualification/submit/"                         //提交广告主资质
	ADVERTISER_UPDATE_BUDGET_URI                                = "/advertiser/update/budget/"                                //更新账户日预算

	AGENT_ADVERTISER_CREATE_URI                                 = "/agent/advertiser/create/"                                 //创建广告主
	AGENT_ADVERTISER_RECHARGE_URI                               = "/agent/advertiser/recharge/"                               //代理商转账
	AGENT_ADVERTISER_REFUND_URI                                 = "/agent/advertiser/refund/"                                 //代理商退款
	AGENT_ADVERTISER_SELECT_URI                                 = "/agent/advertiser/select/"                                 //广告主列表
	AGENT_ADVERTISER_UPDATE_URI                                 = "/agent/advertiser/update/"                                 //修改广告主
	AGENT_CHILD_AGENT_SELECT_URI                                = "/agent/child_agent/select/"                                //二级代理商列表
	AGENT_INFO_URI                                              = "/agent/info/"                                              //获取代理商信息

	ASYNC_TASK_CREATE_URI                                       = "/async_task/create/"                                       //创建异步任务
	ASYNC_TASK_DOWNLOAD_URI                                     = "/async_task/download/"                                     //下载任务结果
	ASYNC_TASK_GET_URI                                          = "/async_task/get/"                                          //获取任务列表

	AUDIENCE_PACKAGE_AD_BIND_URI                                = "/audience_package/ad/bind/"                                //计划绑定定向包
	AUDIENCE_PACKAGE_AD_UNBIND_URI                              = "/audience_package/ad/unbind/"                              //定向包解绑
	AUDIENCE_PACKAGE_CREATE_URI                                 = "/audience_package/create/"                                 //创建定向包
	AUDIENCE_PACKAGE_DELETE_URI                                 = "/audience_package/delete/"                                 //删除定向包
	AUDIENCE_PACKAGE_GET_URI                                    = "/audience_package/get/"                                    //获取定向包
	AUDIENCE_PACKAGE_UPDATE_URI                                 = "/audience_package/update/"                                 //更新定向包

	CAMPAIGN_CREATE_URI                                         = "/campaign/create/"                                      //广告组
	CAMPAIGN_GET_URI                                            = "/campaign/get/"                                            //获取广告组
	CAMPAIGN_UPDATE_URI                                         = "/campaign/update/"                                         //修改广告组
	CAMPAIGN_UPDATE_STATUS_URI                                  = "/campaign/update/status/"                                  //广告组更新状态

	CLUE_COUPON_CODE_CONSUME_URI                                = "/clue/coupon/code/consume/"                                //核销券码
	CLUE_COUPON_CODE_GET_URI                                    = "/clue/coupon/code/get/"                                    //查询券码记录
	CLUE_COUPON_CODE_UPLOAD_URI                                 = "/clue/coupon/code/upload/"                                 //上传券码接口
	CLUE_COUPON_CREATE_URI                                      = "/clue/coupon/create/"                                      //创建卡券
	CLUE_COUPON_DETAIL_URI                                      = "/clue/coupon/detail/"                                      //获取卡券详情
	CLUE_COUPON_EMPLOYEE_CREATE_URI                             = "/clue/coupon/employee/create/"                             //添加核销员
	CLUE_COUPON_EMPLOYEE_DELETE_URI                             = "/clue/coupon/employee/delete/"                             //删除核销员
	CLUE_COUPON_EMPLOYEE_GET_URI                                = "/clue/coupon/employee/get/"                                //查询核销员
	CLUE_COUPON_GET_URI                                         = "/clue/coupon/get/"                                         //获取卡券列表
	CLUE_COUPON_UPDATE_URI                                      = "/clue/coupon/update/"                                      //编辑卡券
	CLUE_FORM_CREATE_URI                                        = "/clue/form/create/"                                        //创建表单
	CLUE_FORM_DELETE_URI                                        = "/clue/form/delete/"                                        //删除表单
	CLUE_FORM_DETAIL_URI                                        = "/clue/form/detail/"                                        //获取表单详情
	CLUE_FORM_LIST_URI                                          = "/clue/form/list/"                                          //获取表单列表
	CLUE_FORM_UPDATE_URI                                        = "/clue/form/update/"                                        //更新表单
	CLUE_SMARTPHONE_CREATE_URI                                  = "/clue/smartphone/create/"                                  //创建智能电话
	CLUE_SMARTPHONE_DELETE_URI                                  = "/clue/smartphone/delete/"                                  //删除智能电话
	CLUE_SMARTPHONE_GET_URI                                     = "/clue/smartphone/get/"                                     //获取智能电话列表
	CLUE_SMARTPHONE_RECORD_URI                                  = "/clue/smartphone/record/"                                  //查询智能电话拨打记录
	CREATIVE_CREATE_V2_URI                                      = "/creative/create_v2/"                                     //广告创意

	CREATIVE_GET_URI                                            = "/creative/get/"                                            //获取创意列表
	CREATIVE_MATERIAL_READ_URI                                  = "/creative/material/read/"                                  //创意素材信息
	CREATIVE_READ_V2_URI                                        = "/creative/read_v2/"                                        //创意详细信息
	CREATIVE_REJECT_REASON_URI                                  = "/creative/reject_reason/"                                  //获取创意审核建议
	CREATIVE_UPDATE_STATUS_URI                                  = "/creative/update/status/"                                  //更改创意状态
	CREATIVE_UPDATE_V2_URI                                      = "/creative/update_v2/"                                      //修改创意信息

	DMP_CUSTOM_AUDIENCE_CALC_URI                                = "/dmp/custom_audience/calc/"                                //运算人群包
	DMP_CUSTOM_AUDIENCE_DELETE_URI                              = "/dmp/custom_audience/delete/"                              //删除人群包
	DMP_CUSTOM_AUDIENCE_LOOKALIKE_URI                           = "/dmp/custom_audience/lookalike/"                           //拓展人群包
	DMP_CUSTOM_AUDIENCE_PUBLISH_URI                             = "/dmp/custom_audience/publish/"                             //发布人群包
	DMP_CUSTOM_AUDIENCE_PUSH_V2_URI                             = "/dmp/custom_audience/push_v2/"                             //推送人群包
	DMP_CUSTOM_AUDIENCE_READ_URI                                = "/dmp/custom_audience/read/"                                //人群包详细信息
	DMP_CUSTOM_AUDIENCE_RULE_URI                                = "/dmp/custom_audience/rule/"                                //规则人群包
	DMP_CUSTOM_AUDIENCE_SELECT_URI                              = "/dmp/custom_audience/select/"                              //人群包列表
	DMP_DATA_SOURCE_CREATE_URI                                  = "/dmp/data_source/create/"                                  //数据源创建
	DMP_DATA_SOURCE_FILE_UPLOAD_URI                             = "/dmp/data_source/file/upload/"                             //数据源文件上传
	DMP_DATA_SOURCE_READ_URI                                    = "/dmp/data_source/read/"                                    //数据源详细信息
	DMP_DATA_SOURCE_UPDATE_URI                                  = "/dmp/data_source/update/"                                  //数据源更新

	DPA_BEHAVIOUR_AVAILABLES_URI                                = "/dpa/behaviour/availables/"                                //获取DPA可用行为
	DPA_CATEGORY_GET_URI                                        = "/dpa/category/get/"                                        //获取DPA分类
	DPA_DETAIL_GET_URI                                          = "/dpa/detail/get/"                                          //获取DPA商品库商品列表
	DPA_DICT_GET_URI                                            = "/dpa/dict/get/"                                            //获取DPA词包
	DPA_META_GET_URI                                            = "/dpa/meta/get/"                                            //获取DPA商品库信息
	DPA_PRODUCT_AVAILABLES_URI                                  = "/dpa/product/availables/"                                  //查询DPA商品库
	DPA_TEMPLATE_GET_URI                                        = "/dpa/template/get/"                                        //获取DPA模板
	DPA_VIDEO_GET_URI                                           = "/dpa/video/get/"                                           //获取 DPA 商品库视频模板

	FILE_IMAGE_AD_URI                                           = "/file/image/ad/"                                           //上传广告图片
	FILE_IMAGE_AD_GET_URI                                       = "/file/image/ad/get/"                                       //获取同主体下广告主图片素材
	FILE_IMAGE_ADVERTISER_URI                                   = "/file/image/advertiser/"                                   //上传广告主图片
	FILE_IMAGE_GET_URI                                          = "/file/image/get/"                                          //获取图片素材
	FILE_MATERIAL_BIND_URI                                      = "/file/material/bind/"                                      //素材推送
	FILE_VIDEO_AD_URI                                           = "/file/video/ad/"                                           //上传视频
	FILE_VIDEO_AD_GET_URI                                       = "/file/video/ad/get/"                                       //获取同主体下广告主视频素材
	FILE_VIDEO_DELETE_URI                                       = "/file/video/delete/"                                       //批量删除视频素材
	FILE_VIDEO_GET_URI                                          = "/file/video/get/"                                          //获取视频素材
	FILE_VIDEO_UPDATE_URI                                       = "/file/video/update/"                                       //更新视频

	KALEIDOSCOPE_JOB_MAGIC_VIDEO_RETARGETING_SUBMIT_URI         = "/kaleidoscope/job/magic_video_retargeting/submit/"         //视频智能裁剪
	KALEIDOSCOPE_JOB_MUSIC_GET_BY_STYLE_SUBMIT_URI              = "/kaleidoscope/job/music_get_by_style/submit/"              //根据音乐风格获取音乐列表
	KALEIDOSCOPE_JOB_RESULT_GET_URI                             = "/kaleidoscope/job/result/get/"                             //获取万花筒任务信息
	KALEIDOSCOPE_JOB_SMART_CUT_SUBMIT_URI                       = "/kaleidoscope/job/smart_cut/submit/"                       //微电影
	KALEIDOSCOPE_JOB_SUPER_RESOLUTION_SUBMIT_URI                = "/kaleidoscope/job/super_resolution/submit/"                //图片超分
	KALEIDOSCOPE_JOB_VIDEO_CONCAT_SUBMIT_URI                    = "/kaleidoscope/job/video_concat/submit/"                    //视频拼接
	KALEIDOSCOPE_JOB_VIDEO_EDGE_CUT_SUBMIT_URI                  = "/kaleidoscope/job/video_edge_cut/submit/"                  //视频边框裁剪
	KALEIDOSCOPE_JOB_VIDEO_SUMMARIZATION_SUBMIT_URI             = "/kaleidoscope/job/video_summarization/submit/"             //视频摘要
	KALEIDOSCOPE_JOB_ZOOM_VIDEO_RETARGETING_TOP_VIEW_SUBMIT_URI = "/kaleidoscope/job/zoom_video_retargeting_top_view/submit/" //TopView方式的视频智能裁剪

	KEYWORD_CREATE_V2_URI                                       = "/keyword/create_v2/"                                       //创建关键词
	KEYWORD_DELETE_V2_URI                                       = "/keyword/delete_v2/"                                       //删除关键词
	KEYWORD_GET_URI                                             = "/keyword/get/"                                             //获取关键词列表
	KEYWORD_UPDATE_V2_URI                                       = "/keyword/update_v2/"                                       //更新关键词

	MAJORDOMO_ADVERTISER_SELECT_URI                             = "/majordomo/advertiser/select/"                             //广告主列表（管家）

	REPORT_AD_GET_URI                                           = "/report/ad/get/"                                           //广告计划数据
	REPORT_ADVERTISER_GET_URI                                   = "/report/advertiser/get/"                                   //广告主数据
	REPORT_AGENT_GET_URI                                        = "/report/agent/get/"                                        //代理商数据（待废弃）
	REPORT_AGENT_GET_V2_URI                                     = "/report/agent/get_v2/"                                     //新版代理商数据
	REPORT_AUDIENCE_AGE_URI                                     = "/report/audience/age/"                                     //年龄数据
	REPORT_AUDIENCE_AWEME_LIST_URI                              = "/report/audience/aweme/list/"                              //抖音达人报表
	REPORT_AUDIENCE_GENDER_URI                                  = "/report/audience/gender/"                                  //性别数据
	REPORT_AUDIENCE_INTEREST_ACTION_LIST_URI                    = "/report/audience/interest_action/list/"                    //行为兴趣报表
	REPORT_AUDIENCE_PROVINCE_URI                                = "/report/audience/province/"                                //省级数据
	REPORT_AUDIENCE_TAG_URI                                     = "/report/audience/tag/"                                     //兴趣数据
	REPORT_CAMPAIGN_GET_URI                                     = "/report/campaign/get/"                                     //广告组数据
	REPORT_CREATIVE_GET_URI                                     = "/report/creative/get/"                                     //广告创意数据
	REPORT_INTEGRATED_GET_URI                                   = "/report/integrated/get/"                                   //多合一数据报表接口
	REPORT_MISTY_GET_URI                                        = "/report/misty/get/"                                        //分级模糊数据
	REPORT_VIDEO_FRAME_GET_URI                                  = "/report/video/frame/get/"                                  //视频互动流失数据
	REPORT_VIDEO_GET_URI                                        = "/report/video/get/"                                        //视频素材报表

	TOOLS_ACTION_TEXT_GET_URI                                   = "/tools/action_text/get/"                                   //行动号召字段内容获取
	TOOLS_ADVERTISER_GOODS_LIST_URI                             = "/tools/advertiser_goods/list/"                             //获取鲁班商品列表
	TOOLS_ADVERTISER_PACKAGE_GET_URI                            = "/tools/advertiser_package/get/"                            //查询极速下载列表
	TOOLS_ADVERTISER_STORE_SEARCH_URI                           = "/tools/advertiser_store/search/"                           //查询门店
	TOOLS_ADVERTISER_STORE_SEARCH_PACK_URI                      = "/tools/advertiser_store/search_pack/"                      //查询门店活动
	TOOLS_ADV_CONVERT_SELECT_URI                                = "/tools/adv_convert/select/"                                //转化ID列表
	TOOLS_AD_CONVERT_CREATE_URI                                 = "/tools/ad_convert/create/"                                 //创建转化ID
	TOOLS_AD_CONVERT_PUSH_URI                                   = "/tools/ad_convert/push/"                                   //转化ID推送
	TOOLS_AD_CONVERT_QUERY_URI                                  = "/tools/ad_convert/query/"                                  //【新】查询计划可用转化id
	TOOLS_AD_CONVERT_READ_URI                                   = "/tools/ad_convert/read/"                                   //查询转化详细信息
	TOOLS_AD_CONVERT_SELECT_URI                                 = "/tools/ad_convert/select/"                                 //【将废弃】查询计划可用转化ID
	TOOLS_AD_CONVERT_UPDATE_URI                                 = "/tools/ad_convert/update/"                                 //修改转化ID
	TOOLS_AD_CONVERT_UPDATE_STATUS_URI                          = "/tools/ad_convert/update_status/"                          //更新转化状态
	TOOLS_AD_PREVIEW_QRCODE_GET_URI                             = "/tools/ad_preview/qrcode_get/"                             //获取广告预览二维码
	TOOLS_AD_QUALITY_GET_URI                                    = "/tools/ad_quality/get/"                                    //查询广告质量度
	TOOLS_AD_RAISE_SET_URI                                      = "/tools/ad_raise/set/"                                      //启动一键起量
	TOOLS_AD_RAISE_ESTIMATE_GET_URI                             = "/tools/ad_raise_estimate/get/"                             //获取起量预估值
	TOOLS_AD_RAISE_RESULT_GET_URI                               = "/tools/ad_raise_result/get/"                               //获取一键起量的后验数据
	TOOLS_AD_RAISE_STATUS_GET_URI                               = "/tools/ad_raise_status/get/"                               //获取当前起量状态
	TOOLS_AD_STAT_EXTRA_INFO_GET_URI                            = "/tools/ad_stat_extra_info/get/"                            //查询广告计划学习期状态
	TOOLS_APP_MANAGEMENT_APP_GET_URI                            = "/tools/app_management/app/get/"                            //查询应用信息
	TOOLS_APP_MANAGEMENT_BOOKING_GET_URI                        = "/tools/app_management/booking/get/"                        //查询游戏信息
	TOOLS_APP_MANAGEMENT_BOOKING_RECORDS_GET_URI                = "/tools/app_management/booking_records/get/"                //查询应用预约记录
	TOOLS_APP_SEARCH_URI                                        = "/tools/app_search/"                                        //查询应用信息
	TOOLS_AWEME_AUTHOR_INFO_GET_URI                             = "/tools/aweme_author_info/get/"                             //查询抖音号id对应的达人信息
	TOOLS_AWEME_BANNED_LIST_URI                                 = "/tools/aweme_banned/list/"                                 //获取屏蔽用户列表
	TOOLS_AWEME_BANNED_CREATE_URI                               = "/tools/aweme_banned_create/"                               //添加屏蔽用户
	TOOLS_AWEME_BANNED_DELETE_URI                               = "/tools/aweme_banned_delete/"                               //删除屏蔽用户
	TOOLS_AWEME_CATEGORY_TOP_AUTHOR_GET_URI                     = "/tools/aweme_category_top_author/get/"                     //查询抖音类目下的推荐达人
	TOOLS_AWEME_INFO_SEARCH_URI                                 = "/tools/aweme_info_search/"                                 //查询抖音帐号和类目信息
	TOOLS_AWEME_MULTI_LEVEL_CATEGORY_GET_URI                    = "/tools/aweme_multi_level_category/get/"                    //查询抖音类目列表
	TOOLS_AWEME_SIMILAR_AUTHOR_SEARCH_URI                       = "/tools/aweme_similar_author_search/"                       //查询抖音类似帐号
	TOOLS_BID_SUGGEST_URI                                       = "/tools/bid/suggest/"                                       //建议日预算及预期成本
	TOOLS_CLUE_CALLBACK_URI                                     = "/tools/clue/callback/"                                     //回传有效线索
	TOOLS_CLUE_FORM_DETAIL_URI                                  = "/tools/clue/form/detail/"                                  //建站工具——查询表单详情
	TOOLS_CLUE_FORM_GET_URI                                     = "/tools/clue/form/get/"                                     //建站工具——查询已有表单列表
	TOOLS_CLUE_GET_URI                                          = "/tools/clue/get/"                                          //获取线索列表
	TOOLS_CLUE_SMART_PHONE_GET_URI                              = "/tools/clue/smart_phone/get/"                              //建站工具——查询已有智能电话
	TOOLS_COMMENT_GET_URI                                       = "/tools/comment/get/"                                       //查询评论
	TOOLS_COMMENT_OPERATE_URI                                   = "/tools/comment/operate/"                                   //评论操作
	TOOLS_COMMENT_TERMS_BANNED_ADD_URI                          = "/tools/comment/terms_banned/add/"                          //添加屏蔽词
	TOOLS_COMMENT_TERMS_BANNED_DELETE_URI                       = "/tools/comment/terms_banned/delete/"                       //删除屏蔽词
	TOOLS_COMMENT_TERMS_BANNED_GET_URI                          = "/tools/comment/terms_banned/get/"                          //获取屏蔽词列表
	TOOLS_COMMENT_TERMS_BANNED_UPDATE_URI                       = "/tools/comment/terms_banned/update/"                       //更新屏蔽词
	TOOLS_COMMENT_REPLY_GET_URI                                 = "/tools/comment_reply/get/"                                 //评论回复获取
	TOOLS_CREATIVE_WORD_CREATE_URI                              = "/tools/creative_word/create/"                              //创建动态创意词包
	TOOLS_CREATIVE_WORD_DELETE_URI                              = "/tools/creative_word/delete/"                              //删除动态创意词包
	TOOLS_CREATIVE_WORD_SELECT_URI                              = "/tools/creative_word/select/"                              //查询动态创意词包
	TOOLS_CREATIVE_WORD_UPDATE_URI                              = "/tools/creative_word/update/"                              //更新动态创意词包
	TOOLS_DIAGNOSIS_AD_CURVE_URI                                = "/tools/diagnosis/ad/curve/"                                //获取计划诊断预估变化趋势
	TOOLS_DIAGNOSIS_AD_GET_URI                                  = "/tools/diagnosis/ad/get/"                                  //获取计划诊断详情
	TOOLS_ESTIMATE_AUDIENCE_URI                                 = "/tools/estimate_audience/"                                 //查询受众预估结果
	TOOLS_IES_ACCOUNT_SEARCH_URI                                = "/tools/ies_account_search/"                                //获取绑定的抖音号
	TOOLS_INDUSTRY_GET_URI                                      = "/tools/industry/get/"                                      //获取行业列表
	TOOLS_INTEREST_ACTION_ACTION_CATEGORY_URI                   = "/tools/interest_action/action/category/"                   //行为类目查询
	TOOLS_INTEREST_ACTION_ACTION_KEYWORD_URI                    = "/tools/interest_action/action/keyword/"                    //行为关键词查询
	TOOLS_INTEREST_ACTION_ID2WORD_URI                           = "/tools/interest_action/id2word/"                           //兴趣行为类目关键词id转词
	TOOLS_INTEREST_ACTION_INTEREST_CATEGORY_URI                 = "/tools/interest_action/interest/category/"                 //兴趣类目查询
	TOOLS_INTEREST_ACTION_INTEREST_KEYWORD_URI                  = "/tools/interest_action/interest/keyword/"                  //兴趣关键词查询
	TOOLS_INTEREST_ACTION_KEYWORD_SUGGEST_URI                   = "/tools/interest_action/keyword/suggest/"                   //获取行为兴趣推荐关键词
	TOOLS_INTEREST_TAGS_CREATE_URI                              = "/tools/interest_tags/create/"                              //创建兴趣词包
	TOOLS_INTEREST_TAGS_DELETE_URI                              = "/tools/interest_tags/delete/"                              //删除兴趣词包
	TOOLS_INTEREST_TAGS_ID2WORD_URI                             = "/tools/interest_tags/id2word/"                             //兴趣关键词ID转词
	TOOLS_INTEREST_TAGS_SELECT_URI                              = "/tools/interest_tags/select/"                              //获取兴趣关键词词包
	TOOLS_INTEREST_TAGS_UPDATE_URI                              = "/tools/interest_tags/update/"                              //更新兴趣词包
	TOOLS_INTEREST_TAGS_WORD2ID_URI                             = "/tools/interest_tags/word2id/"                             //兴趣关键词词转ID
	TOOLS_KEY_ACTION_GET_URI                                    = "/tools/key_action/get/"                                    //获取活动记录
	TOOLS_LANDING_GROUP_CREATE_URI                              = "/tools/landing_group/create/"                              //创建落地页组
	TOOLS_LANDING_GROUP_GET_URI                                 = "/tools/landing_group/get/"                                 //获取落地页组
	TOOLS_LANDING_GROUP_SITE_OPT_STATUS_UPDATE_URI              = "/tools/landing_group/site_opt_status/update/"              //更新落地页组站点状态
	TOOLS_LANDING_GROUP_UPDATE_URI                              = "/tools/landing_group/update/"                              //更新落地页组信息
	TOOLS_LOG_SEARCH_URI                                        = "/tools/log_search/"                                        //日志查询
	TOOLS_PIC_TO_VIDEO_MUSIC_GET_URI                            = "/tools/pic_to_video/music/get/"                            //获取音乐列表
	TOOLS_PIC_TO_VIDEO_STATUS_GET_URI                           = "/tools/pic_to_video/status/get/"                           //获取任务状态
	TOOLS_PIC_TO_VIDEO_TASK_CREATE_URI                          = "/tools/pic_to_video/task/create/"                          //创建图片转视频任务
	TOOLS_PLAYABLE_GRANT_URI                                    = "/tools/playable/grant/"                                    //推送试玩素材
	TOOLS_PLAYABLE_GRANT_RESULT_URI                             = "/tools/playable/grant/result/"                             //获取试玩素材推送结果
	TOOLS_PLAYABLE_GRANTABLE_ADV_LIST_URI                       = "/tools/playable/grantable/adv_list/"                       //获取试玩素材可推送列表
	TOOLS_PLAYABLE_SAVE_URI                                     = "/tools/playable/save/"                                     //保存试玩素材
	TOOLS_PLAYABLE_UPLOAD_URI                                   = "/tools/playable/upload/"                                   //试玩素材上传
	TOOLS_PLAYABLE_VALIDATE_URI                                 = "/tools/playable/validate/"                                 //试玩素材上传校验结果
	TOOLS_PLAYABLE_LIST_GET_URI                                 = "/tools/playable_list/get/"                                 //获取试玩素材列表
	TOOLS_PRIVATIVE_WORD_AD_ADD_URI                             = "/tools/privative_word/ad/add/"                             //批量新增计划否定词
	TOOLS_PRIVATIVE_WORD_AD_UPDATE_URI                          = "/tools/privative_word/ad/update/"                          //设置计划否定词
	TOOLS_PRIVATIVE_WORD_CAMPAIGN_ADD_URI                       = "/tools/privative_word/campaign/add/"                       //批量新增组否定词
	TOOLS_PRIVATIVE_WORD_CAMPAIGN_UPDATE_URI                    = "/tools/privative_word/campaign/update/"                    //设置组否定词
	TOOLS_PRIVATIVE_WORD_GET_URI                                = "/tools/privative_word/get/"                                //获取否定词列表
	TOOLS_PROCEDURAL_PACKAGE_GET_URI                            = "/tools/procedural_package/get/"                            //查询程序化创意包
	TOOLS_REGION_GET_URI                                        = "/tools/region/get/"                                        //获取地域列表
	TOOLS_RTA_BIND_URI                                          = "/tools/rta/bind/"                                          //绑定RTA策略
	TOOLS_RTA_GET_URI                                           = "/tools/rta/get/"                                           //获取可用的RTA策略
	TOOLS_RTA_GET_INFO_URI                                      = "/tools/rta/get_info/"                                      //获取RTA策略数据
	TOOLS_RTA_UNBIND_URI                                        = "/tools/rta/unbind/"                                        //解绑RTA策略
	TOOLS_SITE_CREATE_URI                                       = "/tools/site/create/"                                       //创建橙子建站站点
	TOOLS_SITE_FORMS_LIST_URI                                   = "/tools/site/forms/list/"                                   //获取落地页预约表单信息
	TOOLS_SITE_GET_URI                                          = "/tools/site/get/"                                          //获取橙子建站站点列表
	TOOLS_SITE_PREVIEW_URI                                      = "/tools/site/preview/"                                      //获取橙子建站站点预览地址
	TOOLS_SITE_READ_URI                                         = "/tools/site/read/"                                         //获取橙子建站站点详细信息
	TOOLS_SITE_UPDATE_URI                                       = "/tools/site/update/"                                       //修改橙子建站站点
	TOOLS_SITE_UPDATE_STATUS_URI                                = "/tools/site/update_status/"                                //更改橙子建站站点状态
	TOOLS_SUBLINK_CREATE_URI                                    = "/tools/sublink/create/"                                    //创建子链
	TOOLS_SUBLINK_DELETE_URI                                    = "/tools/sublink/delete/"                                    //删除子链
	TOOLS_SUBLINK_LIST_URI                                      = "/tools/sublink/list/"                                      //获取子链列表
	TOOLS_SUBLINK_UPDATE_URI                                    = "/tools/sublink/update/"                                    //编辑子链
	TOOLS_THIRD_SITE_CREATE_URI                                 = "/tools/third_site/create/"                                 //创建第三方落地页站点
	TOOLS_THIRD_SITE_DELETE_URI                                 = "/tools/third_site/delete/"                                 //删除第三方落地页站点
	TOOLS_THIRD_SITE_GET_URI                                    = "/tools/third_site/get/"                                    //获取第三方落地页站点列表
	TOOLS_THIRD_SITE_PREVIEW_URI                                = "/tools/third_site/preview/"                                //获取第三方落地页预览地址
	TOOLS_THIRD_SITE_UPDATE_URI                                 = "/tools/third_site/update/"                                 //修改第三方落地页站点
	TOOLS_UNION_FLOW_PACKAGE_CREATE_URI                         = "/tools/union/flow_package/create/"                         //创建穿山甲流量包
	TOOLS_UNION_FLOW_PACKAGE_DELETE_URI                         = "/tools/union/flow_package/delete/"                         //删除穿山甲流量包
	TOOLS_UNION_FLOW_PACKAGE_GET_URI                            = "/tools/union/flow_package/get/"                            //获取穿山甲流量包
	TOOLS_UNION_FLOW_PACKAGE_REPORT_URI                         = "/tools/union/flow_package/report/"                         //查看rit数据
	TOOLS_UNION_FLOW_PACKAGE_UPDATE_URI                         = "/tools/union/flow_package/update/"                         //修改穿山甲流量包
	TOOLS_VIDEO_COVER_SUGGEST_URI                               = "/tools/video_cover/suggest/"                               //获取视频智能封面

	USER_INFO_URI                                               = "/user/info/"                                               //获取token对应的user信息

	OPEN_API_OAUTH2_ACCESS_TOKEN_URI                            = "open_api/oauth2/access_token/"                             //获取Access Token
	OPEN_API_OAUTH2_ADVERTISER_GET_URI                          = "open_api/oauth2/advertiser/get/"                           //获取已授权账户
	OPEN_API_OAUTH2_REFRESH_TOKEN_URI                           = "open_api/oauth2/refresh_token/"                            //刷新Refresh Token

)
